spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myBox
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
file:
  dir: C:\Users\kihae\study-project\file